PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE products (
	id INTEGER PRIMARY KEY AUTOINCREMENT
, name VARCHAR(50) NOT NULL, price REAL NOT NULL, localstock INTEGER NOT NULL, providerprice REAL NOT NULL, providerstock INTEGER NOT NULL);
COMMIT;
